/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRegisterRouteImport } from './routes/_app.register'
import { Route as AppRecognitionRouteImport } from './routes/_app.recognition'
import { Route as AppProxyRouteImport } from './routes/_app.proxy'
import { Route as AppPreprocessingRouteImport } from './routes/_app.preprocessing'
import { Route as AppLivenessRouteImport } from './routes/_app.liveness'
import { Route as AppLiveRouteImport } from './routes/_app.live'
import { Route as AppDetectionRouteImport } from './routes/_app.detection'
import { Route as AppDatabaseRouteImport } from './routes/_app.database'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppRecognitionRoute = AppRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => AppRoute,
} as any)
const AppProxyRoute = AppProxyRouteImport.update({
  id: '/proxy',
  path: '/proxy',
  getParentRoute: () => AppRoute,
} as any)
const AppPreprocessingRoute = AppPreprocessingRouteImport.update({
  id: '/preprocessing',
  path: '/preprocessing',
  getParentRoute: () => AppRoute,
} as any)
const AppLivenessRoute = AppLivenessRouteImport.update({
  id: '/liveness',
  path: '/liveness',
  getParentRoute: () => AppRoute,
} as any)
const AppLiveRoute = AppLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AppRoute,
} as any)
const AppDetectionRoute = AppDetectionRouteImport.update({
  id: '/detection',
  path: '/detection',
  getParentRoute: () => AppRoute,
} as any)
const AppDatabaseRoute = AppDatabaseRouteImport.update({
  id: '/database',
  path: '/database',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/database': typeof AppDatabaseRoute
  '/detection': typeof AppDetectionRoute
  '/live': typeof AppLiveRoute
  '/liveness': typeof AppLivenessRoute
  '/preprocessing': typeof AppPreprocessingRoute
  '/proxy': typeof AppProxyRoute
  '/recognition': typeof AppRecognitionRoute
  '/register': typeof AppRegisterRoute
  '/reports': typeof AppReportsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/database': typeof AppDatabaseRoute
  '/detection': typeof AppDetectionRoute
  '/live': typeof AppLiveRoute
  '/liveness': typeof AppLivenessRoute
  '/preprocessing': typeof AppPreprocessingRoute
  '/proxy': typeof AppProxyRoute
  '/recognition': typeof AppRecognitionRoute
  '/register': typeof AppRegisterRoute
  '/reports': typeof AppReportsRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/database': typeof AppDatabaseRoute
  '/_app/detection': typeof AppDetectionRoute
  '/_app/live': typeof AppLiveRoute
  '/_app/liveness': typeof AppLivenessRoute
  '/_app/preprocessing': typeof AppPreprocessingRoute
  '/_app/proxy': typeof AppProxyRoute
  '/_app/recognition': typeof AppRecognitionRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/database'
    | '/detection'
    | '/live'
    | '/liveness'
    | '/preprocessing'
    | '/proxy'
    | '/recognition'
    | '/register'
    | '/reports'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/database'
    | '/detection'
    | '/live'
    | '/liveness'
    | '/preprocessing'
    | '/proxy'
    | '/recognition'
    | '/register'
    | '/reports'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/sitemap.xml'
    | '/_app/database'
    | '/_app/detection'
    | '/_app/live'
    | '/_app/liveness'
    | '/_app/preprocessing'
    | '/_app/proxy'
    | '/_app/recognition'
    | '/_app/register'
    | '/_app/reports'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recognition': {
      id: '/_app/recognition'
      path: '/recognition'
      fullPath: '/recognition'
      preLoaderRoute: typeof AppRecognitionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/proxy': {
      id: '/_app/proxy'
      path: '/proxy'
      fullPath: '/proxy'
      preLoaderRoute: typeof AppProxyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preprocessing': {
      id: '/_app/preprocessing'
      path: '/preprocessing'
      fullPath: '/preprocessing'
      preLoaderRoute: typeof AppPreprocessingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/liveness': {
      id: '/_app/liveness'
      path: '/liveness'
      fullPath: '/liveness'
      preLoaderRoute: typeof AppLivenessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/live': {
      id: '/_app/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof AppLiveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/detection': {
      id: '/_app/detection'
      path: '/detection'
      fullPath: '/detection'
      preLoaderRoute: typeof AppDetectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/database': {
      id: '/_app/database'
      path: '/database'
      fullPath: '/database'
      preLoaderRoute: typeof AppDatabaseRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDatabaseRoute: typeof AppDatabaseRoute
  AppDetectionRoute: typeof AppDetectionRoute
  AppLiveRoute: typeof AppLiveRoute
  AppLivenessRoute: typeof AppLivenessRoute
  AppPreprocessingRoute: typeof AppPreprocessingRoute
  AppProxyRoute: typeof AppProxyRoute
  AppRecognitionRoute: typeof AppRecognitionRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppReportsRoute: typeof AppReportsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDatabaseRoute: AppDatabaseRoute,
  AppDetectionRoute: AppDetectionRoute,
  AppLiveRoute: AppLiveRoute,
  AppLivenessRoute: AppLivenessRoute,
  AppPreprocessingRoute: AppPreprocessingRoute,
  AppProxyRoute: AppProxyRoute,
  AppRecognitionRoute: AppRecognitionRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppReportsRoute: AppReportsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
